# Generated by Django 4.2.4 on 2023-12-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_delete_verificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image1',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
    ]
