# Generated by Django 5.0 on 2024-01-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image3',
            field=models.ImageField(null=True, upload_to='base/uploads'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image1',
            field=models.ImageField(null=True, upload_to='base/uploads'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(null=True, upload_to='base/uploads'),
        ),
    ]
