# Generated by Django 5.0 on 2024-01-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_is_special_room_room_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
    ]
