# Generated by Django 5.0 on 2024-01-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, null=True),
        ),
    ]
